# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: aula-de-github-actions

jobs:
  Atualizar-README:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: dar um push no README.md
        run: |
          git config --local user.name "github"
          git config --local user.email "github@users.noreply.github.com"
          git add README.md
          git commit -m "Re-build README.md"
          git push origin




